name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh command via HOST IP, HOST USERNAME and SSH PRIVATE KEY
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf PalaoCorona-frontend
            rm -rf /var/www/palaocorona.xyz/*

            git clone -b master https://${{ secrets.GITHUB_TOKEN }}@github.com/YAS-opensource/PalaoCorona-frontend.git
            cp -r PalaoCorona-frontend/* /var/www/palaocorona.xyz
